AWSTemplateFormatVersion: '2010-09-09'
Description: Secure demo template
Resources:
  PrivateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
